version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: CET
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: org.springframework:spring-webmvc
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.auth0:jwks-rsa
    versions:
    - 0.15.0
    - 0.17.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.springframework.security:spring-security-test
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.springframework.security:spring-security-web
    versions:
    - 5.4.2
    - 5.4.4
    - 5.4.5
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
